### ISSUE TITLE
IOs compatibility

### ISSUE THREAD

**Issue by pimjansen** [fearfm/website#35]
It seems that the website is not rendering well on IOS. The image is stretched down and when you play the stream it opens a new window with a full page livestream instead of just playing it on the website itself.

**Comment by bwestpha** [comment]
The Fullscreen issue is related to a missing configuration parameter. Solve it already. Looking for the stretching issue now

**Comment by pimjansen** [comment]
@bwestpha the image is defined as width 100% so i expect it to scale horizontally but somehow it is doing the same vertically which is a bit weird imo. It should at least respect its original image dimensions

**Comment by bwestpha** [comment]
The differences begin on a very top level of the div-elements:

![image](https://user-images.githubusercontent.com/5863661/93687403-f5556a00-fabd-11ea-9946-6a1b07c5b69f.png)
The calculated height of the boxes is very different:

just to show this i bordered them white:
![image](https://user-images.githubusercontent.com/5863661/93687423-27ff6280-fabe-11ea-8488-601d1a6d0d29.png)

On webkit the element fills the whole viewpoint, on chrome it does not. i have no idea how to influence this, since this is handled by the Mui Grid component , @pimjansen right?

**Comment by bwestpha** [comment]
#44 should be solved by this.
